apiVersion: compute.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  name: sooraj-vm-1
spec:
  providerConfigRef:
    name: default

  forProvider:
    machineType: e2-micro
    zone: us-central1-a

    deletionProtection: false   # ← REQUIRED

    bootDisk:
      - initializeParams:
          image: debian-cloud/debian-12

    networkInterface:
      - subnetworkRef:
          name: sooraj-subnet-1

    tags:
      - web
      - demo
