apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  name: sooraj-demo-vpc
spec:
  providerConfigRef:
    name: default
  forProvider:
    autoCreateSubnetworks: false
    routingMode: REGIONAL
